### ISSUE TITLE
Not working outside of "memory" with this concrete string

### ISSUE THREAD

**Issue by xperiments** [gloryknight/LZstr#1] opened 2018-12-02 00:04 UTC
`<path d="M15.15 11.21H9.82V5.88l-3 4.34-4.36-2.41.44.82a7.41 7.41 0 0 1 5 7 7.38 7.38 0 0 1-.45 2.51l1.36-2 4.36 2.38-2.38-4.36z" data-color="color-2" opacity=".25"/><path d="M5.86 20.75h-.07a.25.25 0 0 1-.18-.24v-5.09H.53a.25.25 0 0 1-.24-.18.25.25 0 0 1 .1-.28l4.15-2.84-2.3-4.19a.25.25 0 0 1 .34-.34l4.17 2.27 2.83-4.15a.25.25 0 0 1 .46.14v5.08h5.08a.25.25 0 0 1 .24.18.25.25 0 0 1-.1.28l-4.15 2.84 2.27 4.16a.25.25 0 0 1-.34.34l-4.13-2.24-2.84 4.15a.25.25 0 0 1-.21.11zM1.3 14.89h4.53a.25.25 0 0 1 .25.25v4.53L8.62 16a.25.25 0 0 1 .33-.08l3.62 2-2-3.62a.25.25 0 0 1 .08-.33l3.68-2.51H9.8a.25.25 0 0 1-.25-.25V6.68L7 10.33a.25.25 0 0 1-.33.08l-3.62-2 2 3.62a.25.25 0 0 1-.08.33z"/><path d="M15.84 8.1h-.07a.25.25 0 0 1-.18-.24V5.42h-2.44a.25.25 0 0 1-.24-.18A.25.25 0 0 1 13 5l2-1.36-1.08-2a.25.25 0 0 1 .34-.34l2 1.08 1.36-2a.25.25 0 0 1 .46.14v2.4h2.42a.25.25 0 0 1 .24.18.25.25 0 0 1-.1.28l-2 1.36 1.08 2a.25.25 0 0 1-.34.34L17.41 6 16 8a.25.25 0 0 1-.16.1zM14 4.91h1.87a.25.25 0 0 1 .25.25V7l1-1.51a.25.25 0 0 1 .33-.08l1.44.79-.79-1.4a.25.25 0 0 1 .08-.33l1.51-1h-1.86a.25.25 0 0 1-.25-.25V1.3l-1 1.51a.25.25 0 0 1-.33.08l-1.44-.79.79 1.44a.25.25 0 0 1-.08.33z"/>`

**Comment by xperiments** [comment] 2018-12-02 00:04
Great work, will be great that you make it work!!!

**Comment by gloryknight** [comment] 2018-12-02 15:33
Thank you for feedback. I checked once again and it works for me: original size: 1171 bytes, compressed size: 274, decompressed size: 1171 bytes. Tested in Chrome, Firefox, node.js, Safari.

Maybe the problem is elsewhere? It is possible that you are using storage which does not store all the bits of the string (like UTF16 localStorage in Safari) to store the variables. This may cause problems while unpacking, since the compressed string is not preserved. Please check this.

Try checking like this:

```
var compresseed = Lc(string);
var original = Ld(compresseed);

console.log(s.length);
console.log(compresseed.length);
console.log(original.length);
```

**Comment by gloryknight** [comment] 2018-12-05 17:53
It seams you have found a solution. I'm closing the issue.

**Closed as completed by gloryknight** 2018-12-05 17:53 UTC
